### ISSUE TITLE
Error on data preview

### ISSUE THREAD

**Issue by pardini01** [eubr-bigsea/limonero#67]
This error happens when I click in the blue "preview" button, located on the "Actions" column, on the /data-sources page. It also happens when I try to preview a recently added data source on the /data-sources/add page:
```
limonero_1      |   File "/usr/local/limonero/limonero/data_source_api.py", line 1669, in get
limonero_1      |     reader = csv.reader(**csv_params)
limonero_1      | TypeError:  expected at least 1 arguments, got 0
```

This is the complete operation log: https://pastebin.com/GEV4nMby

I am running limonero from a locally built Docker image, with the latest version of the source code, on a Ubuntu Server 20.04 host.

**Comment by waltersf** [comment]
Did you click the "Infer Schema" before clicking the Preview button? Also, did you inform the column delimiter? Anyway, it is a bug, at least code must handle the error and display an informative message.

**Comment by pardini01** [comment]
Yes, the column delimiter was correctly informed and I clicked the "infer schema" button. The attributes are also correctly displayed at the "Attributes" tab, on the /data-soures/<id> page. The web interface only displays an "Internal server error" card.

**Comment by waltersf** [comment]
Fixed
